# .github/workflows/main.yml

on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: S.Elkaramany1@uni.brighton.ac.uk # replace me
        MAX_DAYS: 535
        MIN_COMMITS_PER_DAY: 1
        MAX_COMMITS_PER_DAY: 5
        INCLUDE_WEEKENDS: false
